language: swift
osx_image: xcode13.2
xcode_workspace: example-ci-cd.xcworkspace
xcode_scheme: example-ci-cd
xcode_destination: platform=iOS Simulator,OS=15.2,name=iPhone X
before_install:
  - bundle install
  - bundle exec pod install --repo-update